### ISSUE TITLE
Two Typos

### ISSUE THREAD

**Issue by KarlFish** [SigurdAngenent/wisconsin-calculus#1]
Typos in Math 234 pdf

Chapter 7  -  Section 12  -  Problem 5
Page 159 in my pdf
The problem refers to 'D', but then each part defines 'R'. 

Page 194 in my pdf
The answer for (VII 4.3) is incorrect. The average y coordinate should be (4R) / (3pi)

**Comment by KarlFish** [comment]
The typo on Page 159 appears in `234/50vectorcalc.tex` on line 1416

The typo on Page 194 appears in `234/answersANDhints.tex` on line 2372

**Comment by SigurdAngenent** [comment]
Thanks for reporting the typos.  The one on page 159 has been fixed.

The answer 2/pi on page 194 is correct.  The number you computed (4/3pi) is the average of y over the half disc, not the half circle.  The disc is a two dimensional region, the circle is a curve.

**Comment by KarlFish** [comment]
Re-doing the math, I get `2/pi` as well. I guess my interpretation of average y coordinate is wrong because it still doesn't make much sense if R was 0.01 meaning the average y coordinate was larger than any y coordinate on the circle.

**Comment by SigurdAngenent** [comment]
The answer has to be proportional to R.  If you set R=1, then the answer is 2/pi.  But if you compute the average y value over the region inside the circle&above the x-axis you get 4/3pi (you have to do a double integral for that interpretation of the problem).

Thanks for posting typos,

Sigurd
